name: aaronallport.com
kramdown:
  input: GFM
highlighter: rouge
pygments: true
exclude:
  - node_modules
  - scss
  - Gruntfile.js
  - gulpfile.js
  - package.json
  - README.md
  - .scss-lint.yml
gems:
  - jekyll-redirect-from
