# Site settings
name: aaronallport.com
email: aaron@aaronallport.com
description: "Virtual home of Aaron Allport, Salesforce Solution Principal from Colchester, UK."
baseurl: ""
url: "https://aaronallport.com"
future: true

# Build settings
kramdown:
  input: GFM
highlighter: rouge
exclude:
  - node_modules
  - scss
  - Gruntfile.js
  - gulpfile.js
  - package.json
  - README.md
  - .scss-lint.yml
paginate: 10

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-paginate
